### ISSUE TITLE
"Auswahl aufheben" shown as caption of blank select values

### ISSUE THREAD

**Issue by AubreyF** [DCCS-IT-Business-Solutions/react-formik-mui#12]
@dccs/react-formik-mui V0.9.5.

Repro: https://codesandbox.io/s/react-formik-mui-testing-4pn0p?fontsize=14&hidenavigation=1&theme=dark

This behavior isn't intentional, is it?

![image](https://user-images.githubusercontent.com/2789037/69303902-870cf600-0bd3-11ea-8ffa-cd3ecfad3c8a.png)

![image](https://user-images.githubusercontent.com/2789037/69303910-8c6a4080-0bd3-11ea-9bea-2895e827a11a.png)

**Comment by mvitzthum** [comment]
@AubreyF  
I think your codesandbox link doesn't work correctly -> it still shows the very first version from 2 days ago :D

At the moment the defaultText is kinda intentional, since our apps are mostly german.

To change to text you can set it yourself:
![image](https://user-images.githubusercontent.com/47003029/69321345-3503b900-0c43-11ea-9b54-e07e37f0b1f6.png)

Or if you don't want a remove-selection menuitem:
![image](https://user-images.githubusercontent.com/47003029/69321389-52d11e00-0c43-11ea-9c6f-0c19ba9061ef.png)

**Comment by AubreyF** [comment]
@mvitzthum It's not quite the same - the -4pn0p sandbox link includes a selection box which shows the German text.

Thanks for your response. I think a blank defaultText (or at least a centrally configurable one) would be preferable to a phrase in German, but I'll just include a manual override in each of my select elements for now.

**Comment by mvitzthum** [comment]
@AubreyF 
Blank default is a good idea. Didn't think about that.
Gonna change it to default-blank tomorrow :)

**Comment by mvitzthum** [comment]
Fixed in version 0.9.7
